### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "idan",
  "email": "idan122@example.com",
  "password": "123456"
}

###
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWE3MzlkOWM2OGI5ODI0NWM5MDA5ZCIsImlhdCI6MTc0MzQxODI2OSwiZXhwIjoxNzQzNDE5MTY5fQ.4Nz42LVY2oXU-GNyNTMYmgJdDjxVzuz-xe7du6zPVWI

###
POST http://localhost:3000/api/users/login
Content-Type: application/json 

{
  "email": "idan122@example.com",
  "password": "123456"
}
###
POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWE3MzlkOWM2OGI5ODI0NWM5MDA5ZCIsImlhdCI6MTc0MzQyMTM4OCwiZXhwIjoxNzQzNDIyMjg4fQ.rHCk6cBTzagqp_w_s048UcMY5uz8OXRlSDHorSX3WVo

{
  "text": "אני מחפש שותף לדירה ברמת גן",
  "image": "https://example.com/image.jpg"
}
###
GET http://localhost:3000/api/posts
###
GET http://localhost:3000/api/posts/mine
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWE3MzlkOWM2OGI5ODI0NWM5MDA5ZCIsImlhdCI6MTc0MzQyMTM4OCwiZXhwIjoxNzQzNDIyMjg4fQ.rHCk6cBTzagqp_w_s048UcMY5uz8OXRlSDHorSX3WVo
###
GET http://localhost:3000/api/posts/user/67ea739d9c68b98245c9009d
